-- AlterTable
ALTER TABLE "Branch" ADD COLUMN "morningShiftHours" DOUBLE PRECISION DEFAULT 6;
ALTER TABLE "Branch" ADD COLUMN "eveningShiftHours" DOUBLE PRECISION DEFAULT 6;
ALTER TABLE "Branch" ADD COLUMN "fullDayShiftHours" DOUBLE PRECISION DEFAULT 10;
ALTER TABLE "Branch" ADD COLUMN "overtimeRateMultiplier" DOUBLE PRECISION DEFAULT 1.5;
