-- Labor & Kitchen Capacity Engine — station-level labor modelling.
--
-- Hand-written rather than generated by `prisma migrate dev`, for the same
-- reason as 20260812050000_add_whatsapp_template: this environment's schema
-- carries unrelated pre-existing drift that a generated migration would
-- otherwise bundle in. Scoped to ONLY the objects this feature introduces.
--
-- Purely additive: three new tables, two new nullable Equipment columns, two
-- new defaulted Branch columns. No existing column is altered or dropped, so
-- this is safe to apply to a live database with orders in flight.

-- CreateTable
CREATE TABLE "KitchenStation" (
    "id" SERIAL NOT NULL,
    "restaurantId" INTEGER NOT NULL,
    "branchId" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "utilizationFactor" DOUBLE PRECISION,
    "capacityPerHour" INTEGER,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdById" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "KitchenStation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MenuItemStationTime" (
    "id" SERIAL NOT NULL,
    "menuItemId" INTEGER NOT NULL,
    "stationId" INTEGER NOT NULL,
    "standardMinutes" DOUBLE PRECISION NOT NULL,
    "observedMinutes" DOUBLE PRECISION,
    "observationCount" INTEGER NOT NULL DEFAULT 0,
    "lastObservedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MenuItemStationTime_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "StaffStationSkill" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "stationId" INTEGER NOT NULL,
    "proficiency" INTEGER NOT NULL DEFAULT 3,
    "speedFactor" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "StaffStationSkill_pkey" PRIMARY KEY ("id")
);

-- AlterTable
-- itemsPerHour is the sustained throughput RATE; the pre-existing
-- itemCapacityCount is a batch SIZE and is left untouched.
ALTER TABLE "Equipment" ADD COLUMN     "itemsPerHour" INTEGER,
ADD COLUMN     "stationId" INTEGER;

-- AlterTable
ALTER TABLE "Branch" ADD COLUMN     "staffUtilizationFactor" DOUBLE PRECISION DEFAULT 0.75,
ADD COLUMN     "targetTicketMinutes" INTEGER DEFAULT 30;

-- CreateIndex
CREATE UNIQUE INDEX "KitchenStation_branchId_code_key" ON "KitchenStation"("branchId", "code");

-- CreateIndex
CREATE INDEX "KitchenStation_restaurantId_idx" ON "KitchenStation"("restaurantId");

-- CreateIndex
CREATE INDEX "KitchenStation_branchId_idx" ON "KitchenStation"("branchId");

-- CreateIndex
CREATE UNIQUE INDEX "MenuItemStationTime_menuItemId_stationId_key" ON "MenuItemStationTime"("menuItemId", "stationId");

-- CreateIndex
CREATE INDEX "MenuItemStationTime_menuItemId_idx" ON "MenuItemStationTime"("menuItemId");

-- CreateIndex
CREATE INDEX "MenuItemStationTime_stationId_idx" ON "MenuItemStationTime"("stationId");

-- CreateIndex
CREATE UNIQUE INDEX "StaffStationSkill_userId_stationId_key" ON "StaffStationSkill"("userId", "stationId");

-- CreateIndex
CREATE INDEX "StaffStationSkill_userId_idx" ON "StaffStationSkill"("userId");

-- CreateIndex
CREATE INDEX "StaffStationSkill_stationId_idx" ON "StaffStationSkill"("stationId");

-- CreateIndex
CREATE INDEX "Equipment_stationId_idx" ON "Equipment"("stationId");

-- AddForeignKey
ALTER TABLE "KitchenStation" ADD CONSTRAINT "KitchenStation_restaurantId_fkey" FOREIGN KEY ("restaurantId") REFERENCES "Restaurant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "KitchenStation" ADD CONSTRAINT "KitchenStation_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
-- SET NULL, not CASCADE: deleting a station must never delete the equipment
-- rows (purchase price, EMI linkage, warranty) that were assigned to it.
ALTER TABLE "Equipment" ADD CONSTRAINT "Equipment_stationId_fkey" FOREIGN KEY ("stationId") REFERENCES "KitchenStation"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MenuItemStationTime" ADD CONSTRAINT "MenuItemStationTime_menuItemId_fkey" FOREIGN KEY ("menuItemId") REFERENCES "MenuItem"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MenuItemStationTime" ADD CONSTRAINT "MenuItemStationTime_stationId_fkey" FOREIGN KEY ("stationId") REFERENCES "KitchenStation"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "StaffStationSkill" ADD CONSTRAINT "StaffStationSkill_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "StaffStationSkill" ADD CONSTRAINT "StaffStationSkill_stationId_fkey" FOREIGN KEY ("stationId") REFERENCES "KitchenStation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
