/**
 * Startup secret validation.
 *
 * Checked once at boot and loudly, rather than lazily on the first request that
 * happens to need a secret. A process that starts, passes its health check, and
 * only fails when an employee tries to sign in is worse than one that refuses
 * to start: the deploy looks green and the breakage surfaces to a person.
 *
 * Nothing here ever prints a secret's value — only whether it is present, and
 * how long it is. A log line is not a safe place for one.
 */

export interface SecretCheck {
  key: string;
  present: boolean;
  /** Blocks startup in production when missing or too weak. */
  requiredInProduction: boolean;
  problem?: string;
}

/**
 * Minimum length for a signing secret.
 *
 * A JWT HMAC key shorter than this is brute-forceable offline by anyone holding
 * a single token. 32 characters is the floor; the deployment should be using
 * something generated by `openssl rand -base64 48`, not a memorable phrase.
 */
const MIN_SECRET_LENGTH = 32;

/** Values that unambiguously mean "nobody set this properly". */
const PLACEHOLDER_PATTERNS = [
  /^changeme/i,
  /^placeholder/i,
  /^your[-_]?secret/i,
  /^secret$/i,
  /^test$/i,
  /^dev[-_]?secret$/i,
  /^xxx+$/i,
];

const looksLikePlaceholder = (value: string) =>
  PLACEHOLDER_PATTERNS.some((pattern) => pattern.test(value.trim()));

const checkSigningSecret = (key: string, requiredInProduction: boolean): SecretCheck => {
  const value = process.env[key];
  if (!value || !value.trim()) {
    return { key, present: false, requiredInProduction, problem: "not set" };
  }
  if (looksLikePlaceholder(value)) {
    return { key, present: true, requiredInProduction, problem: "looks like a placeholder value" };
  }
  if (value.length < MIN_SECRET_LENGTH) {
    return {
      key,
      present: true,
      requiredInProduction,
      problem: `only ${value.length} characters — needs at least ${MIN_SECRET_LENGTH}`,
    };
  }
  return { key, present: true, requiredInProduction };
};

export const inspectSecrets = (): SecretCheck[] => [
  checkSigningSecret("JWT_SECRET", true),
  checkSigningSecret("INTERNAL_JWT_SECRET", true),
];

/**
 * Called once from the server entry point, before it starts listening.
 *
 * In production a problem is fatal. Outside production it is a warning, because
 * a developer running the restaurant apps locally should not be forced to
 * invent an internal-console secret they will never use — but the warning names
 * exactly what is wrong so it does not become background noise.
 */
export const assertSecretsConfigured = (): void => {
  const isProduction = process.env.NODE_ENV === "production";
  const problems = inspectSecrets().filter((check) => check.problem);

  if (!problems.length) return;

  const lines = problems.map((check) => `  - ${check.key}: ${check.problem}`);

  if (isProduction) {
    console.error(
      "\n[secrets] Refusing to start. The following are required in production:\n" +
        lines.join("\n") +
        "\n\n  Generate one with:  openssl rand -base64 48\n" +
        "  Set it in the deployment's environment configuration — never in source control.\n",
    );
    // Exit rather than throw: a throw here would be caught by the process's
    // unhandledRejection handler and reported as a crash, which reads like a
    // bug rather than like a configuration error someone needs to fix.
    process.exit(1);
  }

  console.warn(
    "\n[secrets] Not production, so starting anyway — but these would block a production deploy:\n" +
      lines.join("\n") +
      "\n",
  );
};
