/**
 * Startup secret validation.
 *
 * Checked once at boot and loudly, rather than lazily on the first request that
 * happens to need a secret. A process that starts, passes its health check, and
 * only fails when an employee tries to sign in is worse than one that refuses
 * to start: the deploy looks green and the breakage surfaces to a person.
 *
 * Nothing here ever prints a secret's value — only whether it is present, and
 * how long it is. A log line is not a safe place for one.
 */

export interface SecretCheck {
  key: string;
  present: boolean;
  /** Blocks startup in production when missing or too weak. */
  requiredInProduction: boolean;
  problem?: string;
  /**
   * How bad it is to be missing in production.
   *
   * `fatal`    — nothing the process does is safe without it. Refuse to start.
   * `degraded` — one named feature stops working. Starting is still the right
   *              call: refusing would turn "signup is broken" into "the whole
   *              restaurant is offline", which is strictly worse for every
   *              owner already signed in.
   */
  severity: "fatal" | "degraded";
  /** What actually stops working, for the `degraded` ones. */
  impact?: string;
}

/**
 * Minimum length for a signing secret.
 *
 * A JWT HMAC key shorter than this is brute-forceable offline by anyone holding
 * a single token. 32 characters is the floor; the deployment should be using
 * something generated by `openssl rand -base64 48`, not a memorable phrase.
 */
const MIN_SECRET_LENGTH = 32;

/** Values that unambiguously mean "nobody set this properly". */
const PLACEHOLDER_PATTERNS = [
  /^changeme/i,
  /^placeholder/i,
  /^your[-_]?secret/i,
  /^secret$/i,
  /^test$/i,
  /^dev[-_]?secret$/i,
  /^xxx+$/i,
];

const looksLikePlaceholder = (value: string) =>
  PLACEHOLDER_PATTERNS.some((pattern) => pattern.test(value.trim()));

const checkSigningSecret = (key: string, requiredInProduction: boolean): SecretCheck => {
  const value = process.env[key];
  const base = { key, requiredInProduction, severity: "fatal" as const };
  if (!value || !value.trim()) {
    return { ...base, present: false, problem: "not set" };
  }
  if (looksLikePlaceholder(value)) {
    return { ...base, present: true, problem: "looks like a placeholder value" };
  }
  if (value.length < MIN_SECRET_LENGTH) {
    return {
      ...base,
      present: true,
      problem: `only ${value.length} characters — needs at least ${MIN_SECRET_LENGTH}`,
    };
  }
  return { ...base, present: true };
};

/**
 * A setting that only needs to be non-blank.
 *
 * Whitespace counts as missing: `SENDGRID_API_KEY=" "` is a value that passes a
 * truthiness check and then fails at the provider, which is the most annoying
 * possible way to be misconfigured.
 */
const checkPresence = (key: string, impact: string): SecretCheck => {
  const value = process.env[key];
  const base = { key, requiredInProduction: true, severity: "degraded" as const, impact };
  if (!value || !value.trim()) return { ...base, present: false, problem: "not set" };
  return { ...base, present: true };
};

export const inspectSecrets = (): SecretCheck[] => [
  checkSigningSecret("JWT_SECRET", true),
  checkSigningSecret("INTERNAL_JWT_SECRET", true),
  // Without these, mailer.ts throws "Email service is not configured" — but not
  // until someone is halfway through creating an account or resetting a
  // password. The whole point of this file is that a deploy should discover
  // that, not a customer.
  checkPresence("SENDGRID_API_KEY", "signup verification and password-reset emails"),
  checkPresence("SENDGRID_FROM_EMAIL", "signup verification and password-reset emails"),
];

/**
 * Called once from the server entry point, before it starts listening.
 *
 * In production a problem is fatal. Outside production it is a warning, because
 * a developer running the restaurant apps locally should not be forced to
 * invent an internal-console secret they will never use — but the warning names
 * exactly what is wrong so it does not become background noise.
 */
export const assertSecretsConfigured = (): void => {
  const isProduction = process.env.NODE_ENV === "production";
  const problems = inspectSecrets().filter((check) => check.problem);

  if (!problems.length) return;

  const describe = (check: SecretCheck) =>
    `  - ${check.key}: ${check.problem}` + (check.impact ? `\n      breaks: ${check.impact}` : "");

  const fatal = problems.filter((check) => check.severity === "fatal");
  const degraded = problems.filter((check) => check.severity === "degraded");

  // Printed whether or not startup continues: a feature being silently off in
  // production is the thing this is here to prevent, and it has to be visible
  // in the deploy log rather than discovered from a support ticket.
  if (degraded.length) {
    console.warn(
      "\n[secrets] Starting, but these features are OFF because their configuration is missing:\n" +
        degraded.map(describe).join("\n") +
        "\n\n  Set them in the deployment's environment configuration and redeploy.\n",
    );
  }

  if (!fatal.length) return;

  const lines = fatal.map(describe);

  if (isProduction) {
    console.error(
      "\n[secrets] Refusing to start. The following are required in production:\n" +
        lines.join("\n") +
        "\n\n  Generate one with:  openssl rand -base64 48\n" +
        "  Set it in the deployment's environment configuration — never in source control.\n",
    );
    // Exit rather than throw: a throw here would be caught by the process's
    // unhandledRejection handler and reported as a crash, which reads like a
    // bug rather than like a configuration error someone needs to fix.
    process.exit(1);
  }

  console.warn(
    "\n[secrets] Not production, so starting anyway — but these would block a production deploy:\n" +
      lines.join("\n") +
      "\n",
  );
};
